Initial refactoring for `stateless_llama.py`
nod-ai/SHARK-Turbine pull request #213
Opened 2023-12-01 01:29 UTC by renxida

This partially addresses #184 #185

2023-12-04 15:07 UTC, renxida commented on python/turbine_models/custom_models/stateless_llama.py
> +def run_vmfb_comparison(args):
Good idea, on it!

2023-12-04 18:11 UTC, dan-garvey requested changes

2023-12-04 18:11 UTC, dan-garvey commented on python/shark_turbine/aot/compiled_module.py
> +        "--iree-opt-const-expr-hoisting=False",
So these flags are something I copy pasted offhandedly from a vicuna.py custom compile command in a google doc somewhere, I don't think they're a canonical solid list to just make a default for all compiled models in turbine. Some of them are probably fine but probably worth looking through.

2023-12-04 18:11 UTC, dan-garvey commented on python/shark_turbine/aot/compiled_module.py
> +            target_backends=["llvm-cpu"],
the target backend should probably be a function argument

2023-12-04 18:11 UTC, dan-garvey commented on python/turbine_models/custom_models/compile_hf_transformer_model.py
> +# TODO (Dan): replace this with a file once I figure out paths on windows exe
This needs to not exist more than once in the whole codebase, and could come from its own python file

2023-12-04 18:11 UTC, dan-garvey commented on python/turbine_models/custom_models/compile_hf_transformer_model.py
> +# TODO (Dan): replace this with a file once I figure out paths on windows exe
(as opposed to json file, which is harder to bundle in an exe)

2023-12-04 18:11 UTC, dan-garvey commented on python/turbine_models/custom_models/stateless_llama_demo.sh
Lets make a python runner wrapper that can do both compile/inference from one cli invocation. Bash scripts aren't os agnostic

2023-12-04 18:13 UTC, dan-garvey commented
> Reading exporter.py and model_builder.py, it sounds like I need to:
> 
> * break `compile_hf_transformer_model()` down further and put as much as I can into `model_builder.py` and `exporter.py` instead.
> * make stateless_llama do the following:
>   
>   * generate & run VMFB by default (potentially making a chat interface as default - - people LOVE chat)
>   * when a special argument is supplied, run the VMFB & torch comparison.
> * maybe remove compile_hf_transformer_model entirely

Can see some of my comments, but broadly nothing model specific should go into exporter.py

Chat functionality already exists in SHARK, which imports this, you can add code to do it here too, but it may be unmercenary.

2023-12-05 18:21 UTC, renxida commented
Current plan:
- move llama specific code out of exporter and into turbine_models/custom_models/export_stateless_llama.py
- continue to reuse as much code as possible from shark_turbine.aot.compiled_module and exporter.py to export
- look at compilation flags
- make iree backend in compiled_module.save_vmfb a parameter
- use loggers to replace print
- i already made a CLI chat interface for LLAMA. Will make that the default when somebody runs `python stateless_llama.py`
- make separate vmfb comparison entrypoint

2023-12-06 19:46 UTC, renxida commented
All of this would be easier to do once we have some end to end tests. I've taken notes on Dan & Ian's comments & will open another PR later.

2023-12-06 19:46 UTC, closed without merging